export const LANDING = '/'
export const MANAGE_MEMBERS = '/manage_members'
export const BRANDING = '/branding'
export const CODE_VALIDATIONS = '/code_validations'
export const SETTINGS = '/settings'
export const NOT_FOUND = '/404'
export const BUILD_INFO = '/buildinfo'
